# Permalinks
permalink:           pretty

# Setup
title:               По поводу и без
tagline:             Do about and for no reason
url:                 https://atremba.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Jekyll plugins (former gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist

markdown:            CommonMark

# and its options
commonmark:
  options:           ["SMART", "FOOTNOTES"]
  extensions:        ["strikethrough", "autolink", "table"]

# Custom variables
# About/contact
author:
  name:              Andrey Tremba
  email:             

# Tracking
google_analytics:    UA-137804514-1