# Permalinks
permalink:           pretty

# Setup
title:               По поводу и без
tagline:             Do about and for no reason
url:                 https://atremba.github.io
paginate:            1
baseurl:             https://atremba.github.io

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Jekyll build options

# Cause a build to fail if there is a YAML syntax error in a page's front matter.
strict_front_matter: true


# Jekyll plugins (former gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist



# Choose a parser for markdown
markdown:            CommonMark

# and its options
commonmark:
  options:           ["SMART", "FOOTNOTES"]
  extensions:        ["strikethrough", "autolink", "table"]


# Custom variables

# About/contact
author:
  name:              Andrey Tremba
  email:             

# Tracking
google_analytics:    UA-137804514-1