# Permalinks
permalink:           pretty

# Setup
title:               По поводу и без
tagline:             Do about and for no reason
url:                 https://atremba.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrey Tremba
  email:             

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist